# Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

# Data Understanding

<table style="width:50%; font-size:12px; border-collapse: collapse; margin: 0 auto; text-align: left;">
  <thead>
    <tr style="background-color:#f2f2f2; text-align:left; color: black;">
      <th style="border:1px solid #ddd;">Attribute</th>
      <th style="border:1px solid #ddd;">Description</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="border:1px solid #ddd;">carID</td><td style="border:1px solid #ddd;">An attribute that contains an identifier for each car</td></tr>
    <tr><td style="border:1px solid #ddd;">Brand</td><td style="border:1px solid #ddd;">The car’s main brand (e.g. Ford, Toyota)</td></tr>
    <tr><td style="border:1px solid #ddd;">model</td><td style="border:1px solid #ddd;">The car model</td></tr>
    <tr><td style="border:1px solid #ddd;">year</td><td style="border:1px solid #ddd;">The year of Registration of the Car</td></tr>
    <tr><td style="border:1px solid #ddd;">mileage</td><td style="border:1px solid #ddd;">The total reported distance travelled by the car (in miles)</td></tr>
    <tr><td style="border:1px solid #ddd;">tax</td><td style="border:1px solid #ddd;">The amount of road tax (in £) that, in 2020, was applicable to the car in question.</td></tr>
    <tr><td style="border:1px solid #ddd;">fuelType</td><td style="border:1px solid #ddd;">Type of Fuel used by the car (Diesel, Petrol, Hybrid, Electric)</td></tr>
    <tr><td style="border:1px solid #ddd;">mpg</td><td style="border:1px solid #ddd;">Average Miles per Gallon</td></tr>
    <tr><td style="border:1px solid #ddd;">engineSize</td><td style="border:1px solid #ddd;">Size of Engine in liters (Cubic Decimeters)</td></tr>
    <tr><td style="border:1px solid #ddd;">paintQuality%</td><td style="border:1px solid #ddd;">The mechanic’s assessment of the cars’ overall paint quality and hull integrity (filled by the mechanic during evaluation)</td></tr>
    <tr><td style="border:1px solid #ddd;">previousOwners</td><td style="border:1px solid #ddd;">Number of previous registered owners of the vehicle</td></tr>
    <tr><td style="border:1px solid #ddd;">hasDamage</td><td style="border:1px solid #ddd;">Boolean marker filled by the seller at the time of registration stating whether the car is damaged or not</td></tr>
    <tr><td style="border:1px solid #ddd;">price</td><td style="border:1px solid #ddd;">The car’s price when purchased by Cars 4 You (in £)</td></tr>
  </tbody>
</table>

## Train

In [2]:
train_cars = pd.read_csv("data/train.csv")
print(f"The train dataset has {train_cars.shape[0]} rows and {train_cars.shape[1]} columns")

The train dataset has 75973 rows and 14 columns

In [3]:
metric_features_train = train_cars.select_dtypes(include=['number']).columns
non_metric_features_train = train_cars.columns.drop(metric_features_train).to_list()

In [4]:
train_cars.head()

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
0,69512,VW,Golf,2016.0,22290,Semi-Auto,28421.0,Petrol,NaN,11.417268,2.0,63.0,4.000000,0.0
1,53000,Toyota,Yaris,2019.0,13790,Manual,4589.0,Petrol,145.0,47.900000,1.5,50.0,1.000000,0.0
2,6366,Audi,Q2,2019.0,24990,Semi-Auto,3624.0,Petrol,145.0,40.900000,1.5,56.0,4.000000,0.0
3,29021,Ford,FIESTA,2018.0,12500,anual,9102.0,Petrol,145.0,65.700000,1.0,50.0,-2.340306,0.0
4,10062,BMW,2 Series,2019.0,22995,Manual,1000.0,Petrol,145.0,42.800000,1.5,97.0,3.000000,0.0

In [5]:
train_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75973 entries, 0 to 75972
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   carID           75973 non-null  int64
 1   Brand           74452 non-null  object
 2   model           74456 non-null  object
 3   year            74482 non-null  float64
 4   price           75973 non-null  int64
 5   transmission    74451 non-null  object
 6   mileage         74510 non-null  float64
 7   fuelType        74462 non-null  object
 8   tax             68069 non-null  float64
 9   mpg             68047 non-null  float64
 10  engineSize      74457 non-null  float64
 11  paintQuality%   74449 non-null  float64
 12  previousOwners  74423 non-null  float64
 13  hasDamage       74425 non-null  float64
dtypes: float64(8), int64(2), object(4)
memory usage: 8.1+ MB

In [6]:
train_cars.duplicated().sum()

0

In [7]:
train_cars.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
carID,75973.0,NaN,NaN,NaN,37986.0,21931.660338,0.0,18993.0,37986.0,56979.0,75972.0
Brand,74452,72,Ford,14808,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model,74456,735,Focus,6353,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,74482.0,NaN,NaN,NaN,2017.096611,2.208704,1970.0,2016.0,2017.0,2019.0,2024.121759
price,75973.0,NaN,NaN,NaN,16881.889553,9736.926322,450.0,10200.0,14699.0,20950.0,159999.0
transmission,74451,40,Manual,38050,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mileage,74510.0,NaN,NaN,NaN,23004.184088,22129.788366,-58540.574478,7423.25,17300.0,32427.5,323000.0
fuelType,74462,34,Petrol,37995,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tax,68069.0,NaN,NaN,NaN,120.329078,65.521176,-91.12163,125.0,145.0,145.0,580.0
mpg,68047.0,NaN,NaN,NaN,55.152666,16.497837,-43.421768,46.3,54.3,62.8,470.8
engineSize,74457.0,NaN,NaN,NaN,1.660136,0.573462,-0.103493,1.2,1.6,2.0,6.6
paintQuality%,74449.0,NaN,NaN,NaN,64.590667,21.021065,1.638913,47.0,65.0,82.0,125.594308
previousOwners,74423.0,NaN,NaN,NaN,1.99458,1.472981,-2.34565,1.0,2.0,3.0,6.258371
hasDamage,74425.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Test

In [9]:
test_cars = pd.read_csv("data/test.csv")
print(f"The test dataset has {test_cars.shape[0]} rows and {test_cars.shape[1]} columns")

The test dataset has 32567 rows and 13 columns

In [10]:
metric_features_test = test_cars.select_dtypes(include=['number']).columns
non_metric_features_test = test_cars.columns.drop(metric_features_test).to_list()

In [11]:
test_cars.head()

,carID,Brand,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
0,89856,Hyundai,I30,2022.878006,Automatic,30700.000000,petrol,205.0,41.5,1.6,61.0,3.0,0.0
1,106581,VW,Tiguan,2017.000000,Semi-Auto,-48190.655673,Petrol,150.0,38.2,2.0,60.0,2.0,0.0
2,80886,BMW,2 Series,2016.000000,Automatic,36792.000000,Petrol,125.0,51.4,1.5,94.0,2.0,0.0
3,100174,Opel,Grandland X,2019.000000,Manual,5533.000000,Petrol,145.0,44.1,1.2,77.0,1.0,0.0
4,81376,BMW,1 Series,2019.000000,Semi-Auto,9058.000000,Diesel,150.0,51.4,2.0,45.0,4.0,0.0

In [12]:
test_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32567 entries, 0 to 32566
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   carID           32567 non-null  int64
 1   Brand           31918 non-null  object
 2   model           31917 non-null  object
 3   year            31914 non-null  float64
 4   transmission    31944 non-null  object
 5   mileage         31878 non-null  float64
 6   fuelType        31911 non-null  object
 7   tax             29259 non-null  float64
 8   mpg             29279 non-null  float64
 9   engineSize      31939 non-null  float64
 10  paintQuality%   31942 non-null  float64
 11  previousOwners  31970 non-null  float64
 12  hasDamage       31970 non-null  float64
dtypes: float64(8), int64(1), object(4)
memory usage: 3.2+ MB

In [13]:
test_cars.duplicated().sum()

0

In [14]:
test_cars.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
carID,32567.0,NaN,NaN,NaN,92256.0,9401.427445,75973.0,84114.5,92256.0,100397.5,108539.0
Brand,31918,64,Ford,6360,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model,31917,593,Focus,2721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,31914.0,NaN,NaN,NaN,2017.102299,2.207969,1991.0,2016.0,2017.0,2019.0,2024.121759
transmission,31944,38,Manual,16312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mileage,31878.0,NaN,NaN,NaN,22952.658921,22132.758713,-58540.574478,7298.25,17225.5,32500.0,279000.0
fuelType,31911,29,Petrol,16113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tax,29259.0,NaN,NaN,NaN,120.569239,65.56057,-91.12163,125.0,145.0,145.0,580.0
mpg,29279.0,NaN,NaN,NaN,55.210728,17.644635,-43.421768,46.3,54.3,62.8,470.8
engineSize,31939.0,NaN,NaN,NaN,1.665377,0.574467,-0.103493,1.2,1.6,2.0,6.6
paintQuality%,31942.0,NaN,NaN,NaN,64.446667,21.142188,1.638913,47.0,65.0,82.0,125.594308
previousOwners,31970.0,NaN,NaN,NaN,2.006118,1.47231,-2.34565,1.0,2.0,3.0,6.258371
hasDamage,31970.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Data Preparation

## Data Inconsistency Fixes

### Filtering Positive Values

In [15]:
neg_count_train = (train_cars[metric_features_train] < 0).any(axis=1).sum()
neg_count_test = (test_cars[metric_features_test] < 0).any(axis=1).sum()

year_sup20_train = (train_cars["year"] > 2020).sum()
year_sup20_test = (test_cars["year"] > 2020).sum()

print(f"Train: {neg_count_train} | Test: {neg_count_test} rows with negative values")
print(f"Train: {year_sup20_train} | Test: {year_sup20_test} rows where year > 2020")

Train: 1226 | Test: 544 rows with negative values
Train: 358 | Test: 180 rows where year > 2020

In [16]:
train_cars = train_cars[(train_cars[metric_features_train] >= 0).all(axis=1) & (train_cars["year"] <=2020)].reset_index(drop=True)
test_cars = test_cars[(test_cars[metric_features_test] >= 0).all(axis=1) & (test_cars["year"] <=2020)].reset_index(drop=True)

print(f"Train: {train_cars.shape[0]} | Test: {test_cars.shape[0]} rows")

Train: 57803 | Test: 24937 rows

In [17]:
train_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57803 entries, 0 to 57802
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   carID           57803 non-null  int64
 1   Brand           56652 non-null  object
 2   model           56648 non-null  object
 3   year            57803 non-null  float64
 4   price           57803 non-null  int64
 5   transmission    56613 non-null  object
 6   mileage         57803 non-null  float64
 7   fuelType        56651 non-null  object
 8   tax             57803 non-null  float64
 9   mpg             57803 non-null  float64
 10  engineSize      57803 non-null  float64
 11  paintQuality%   57803 non-null  float64
 12  previousOwners  57803 non-null  float64
 13  hasDamage       57803 non-null  float64
dtypes: float64(8), int64(2), object(4)
memory usage: 6.2+ MB

In [18]:
test_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24937 entries, 0 to 24936
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   carID           24937 non-null  int64
 1   Brand           24442 non-null  object
 2   model           24445 non-null  object
 3   year            24937 non-null  float64
 4   transmission    24466 non-null  object
 5   mileage         24937 non-null  float64
 6   fuelType        24422 non-null  object
 7   tax             24937 non-null  float64
 8   mpg             24937 non-null  float64
 9   engineSize      24937 non-null  float64
 10  paintQuality%   24937 non-null  float64
 11  previousOwners  24937 non-null  float64
 12  hasDamage       24937 non-null  float64
dtypes: float64(8), int64(1), object(4)
memory usage: 2.5+ MB

### Missing Values

In [19]:
def fill_missing_values(df, non_metric_features):
    for i in non_metric_features:
        if i == "fuelType":
            df[i] = df[i].fillna("other")
        else:
            df[i] = df[i].fillna("unknown")
    return df

In [20]:
train_cars = fill_missing_values(train_cars, non_metric_features_train)
test_cars = fill_missing_values(test_cars, non_metric_features_test)

print(f"Train: {train_cars.isna().sum().sum()} | Test: {test_cars.isna().sum().sum()} missing values")

Train: 0 | Test: 0 missing values

### Data Type and String Cleaning

In [21]:
def convert_to_int(df, cols):
    df = df.copy()
    df[cols] = df[cols].astype(int)
    return df

In [22]:
cols = ["year", "previousOwners", "hasDamage"]

train_cars = convert_to_int(train_cars, cols)
test_cars = convert_to_int(test_cars, cols)

In [23]:
brand_mapping= {
        #ford
        "or":"ford", "for":"ford", "ord":"ford",
        #vw
        "w":"vw", "v":"vw",
        #opel
        "ope":"opel", "pel":"opel", "pe":"opel",
        #mercedes
        "ercedes":"mercedes", "mercede":"mercedes", "ercede":"mercedes",
        #bmw
        "bm":"bmw", "mw":"bmw",
        #audi
        "udi":"audi", "aud":"audi", "ud":"audi",
        #toyota
        "oyota":"toyota", "toyot":"toyota",
        #skoda
        "skod":"skoda", "kod":"skoda", "koda":"skoda",
        #hyundai
        "yundai":"hyundai", "hyunda":"hyundai", "yunda":"hyundai"
}

transmission_mapping= {
    #manual
    "anual":"manual", "manua":"manual", "anua":"manual",
    #semi-auto
    "semi-aut":"semi-auto", "emi-auto":"semi-auto", "emi-aut":"semi-auto",
    #automatic
    "automati":"automatic", "utomatic":"automatic", "utomati":"automatic", "automati":"automatic",
    #unknown
    "unknow":"unknown", "nknown":"unknown", "nknow":"unknown", "nknow":"unknown", 
}

fuel_mapping= {
    #petrol
    "petro":"petrol", "etrol":"petrol", "etro":"petrol", 
    #diesel
    "iesel":"diesel", "diese":"diesel", "iese":"diesel",
    #hybrid
    "hybri":"hybrid", "ybrid":"hybrid",
    #other
    "othe":"other", "ther":"other"
} 

def string_cleaning(df, non_metric_features):
    df = df.copy()
    
    mappings = {'Brand': brand_mapping,'transmission': transmission_mapping,'fuelType': fuel_mapping}

    df[non_metric_features] = df[non_metric_features].apply(lambda x: x.str.lower().str.replace(' ', ''))
    
    for col, mapping in mappings.items():
        df[col] = df[col].apply(lambda x: mapping.get(x, x))
    
    return df

In [24]:
train_cars = string_cleaning(train_cars, non_metric_features_train)
test_cars = string_cleaning(test_cars, non_metric_features_test)

### Problematic Values

In [ ]:
#df.loc[df['mpg'] > 150, 'mpg'] = pd.NA  # remove outliers
#df['mpg'] = df.groupby('fuelType')['mpg'].transform(lambda x: x.fillna(x.median()))

In [49]:
brand_model_mean = train_cars[train_cars['engineSize'] != 0].groupby(['Brand', 'model'])['engineSize'].mean()

def fill_engine_size(group, mean_bm = brand_model_mean):
    non_zero_values = group[group != 0].unique()

    if len(non_zero_values) > 0:
        group = group.replace(0, non_zero_values[0])
    
    else:
        brand, model = group.name[0], group.name[1]
        if (brand, model) in mean_bm:
            group = group.replace(0, mean_bm[(brand, model)])
                   
    return group

train_cars['engineSize'] = train_cars.groupby(['Brand', 'model', 'year'])['engineSize'].transform(fill_engine_size)
test_cars['engineSize'] = test_cars.groupby(['Brand', 'model', 'year'])['engineSize'].transform(fill_engine_size)

In [55]:
train_cars[train_cars["engineSize"] == 0]

# 2.5 L (≈ 2.5) — o modelo C230 de 2007 tem cilindrada de 2 496 cc (≈ 2.5 L) para o motor a gasolina
# 0.647 L (≈ 0.65) — se for o modelo BMW i3 com Range Extender, o motor a combustão tem 647 cc

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
23588,37949,mercedes,230,2007,4500,automatic,94000.0,petrol,520.0,29.4,0.0,80.0,2,0
39027,14512,bmw,i,2017,19000,automatic,23983.0,hybrid,0.0,470.8,0.0,95.0,4,0

In [ ]:
train_cars.query("paintQuality% == 125.8")

In [ ]:
train_cars["paintQuality%"] = train_cars["paintQuality%"].clip(upper=100)
test_cars["paintQuality%"] = test_cars["paintQuality%"].clip(upper=100)

In [67]:
train_cars[(train_cars["tax"] == 0) & (train_cars["fuelType"] != "electric")]

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
15,34015,hyundai,i30,2016,7500,manual,51236.0,diesel,0.0,72.4,1.6,94.0,4,0
22,55065,toyota,c-hr,2017,15490,automatic,59000.0,hybrid,0.0,74.3,1.8,95.0,2,0
50,54783,toyota,yaris,2014,10490,automatic,34528.0,hybrid,0.0,80.7,1.5,79.0,1,0
95,15550,ford,fiesta,2016,9500,manual,14879.0,petrol,0.0,65.7,1.0,97.0,1,0
111,32318,hyundai,i30,2015,7698,manual,35259.0,diesel,0.0,78.4,1.6,90.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57699,21976,ford,fiesta,2016,8600,manual,19873.0,petrol,0.0,54.3,1.2,33.0,2,0
57708,49080,skoda,octavia,2014,10990,semi-auto,64501.0,diesel,0.0,62.8,2.0,35.0,3,0
57724,52992,toyota,aygo,2016,8550,manual,20680.0,petrol,0.0,69.0,1.0,66.0,2,0
57731,30535,ford,fiesta,2016,8990,manual,46000.0,other,0.0,65.7,1.0,88.0,2,0
57768,23897,ford,focus,2015,10495,manual,37231.0,diesel,0.0,70.6,2.0,97.0,2,0

In [76]:
bmyf_tax_mode = train_cars[train_cars['tax'] != 0].groupby(['Brand', 'model','year','fuelType'])['tax'].agg(lambda x: x.mode().iloc[0]).to_dict()

brand_fuel_tax_mode = train_cars[train_cars['tax'] != 0].groupby(['Brand','fuelType'])['tax'].agg(lambda x: x.mode().iloc[0]).to_dict()

fuel_mean = train_cars[train_cars['tax'] != 0].groupby(['fuelType'])['tax'].mean()

def fill_tax(row, mean_bmy=bmyf_tax_mode, mean_b=brand_fuel_tax_mode, mean_fuel=fuel_mean):
    if row['tax'] != 0 or row["fuelType"] == "electric" :
        return row['tax']
    
    key_specific = (row['Brand'], row['model'], row['year'], row['fuelType'])
    key_general = (row['Brand'], row['fuelType'])

    if key_specific in mean_bmy:
        return mean_bmy[key_specific]
    elif key_general in mean_b:
        return mean_b[key_general]
    else:
        return mean_fuel[row["fuelType"]]
        


train_cars['tax'] = train_cars.apply(fill_tax, axis=1)
test_cars["tax"] = test_cars.apply(fill_tax, axis=1)

In [101]:
train_cars[train_cars["mpg"] == 470.8]

,carID,Brand,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,paintQuality%,previousOwners,hasDamage
3100,13075,bmw,i3,2015,15498,automatic,33931.0,hybrid,135.0,470.8,0.600000,31.0,4,0
4012,12640,bmw,i3,2017,19500,automatic,23956.0,other,135.0,470.8,0.600000,53.0,1,0
5318,12786,unknown,i3,2015,17400,automatic,29465.0,electric,0.0,470.8,3.822758,67.0,2,0
13900,8993,bmw,i3,2016,18999,automatic,9990.0,other,145.0,470.8,0.600000,44.0,0,0
14252,12853,bmw,i3,2017,21898,automatic,10839.0,hybrid,135.0,470.8,0.600000,31.0,4,0
16299,12090,bmw,i3,2016,19490,automatic,8421.0,hybrid,135.0,470.8,0.600000,31.0,4,0
19002,13378,bmw,i3,2015,17481,automatic,9886.0,hybrid,135.0,470.8,0.600000,44.0,0,0
22516,12269,bmw,i3,2017,19980,automatic,26965.0,hybrid,135.0,470.8,0.600000,81.0,3,0
25678,11532,bmw,i3,2016,16500,automatic,35446.0,hybrid,135.0,470.8,0.600000,59.0,3,0
27899,9737,bmw,i3,2014,14495,automatic,34539.0,hybrid,135.0,470.8,0.600000,42.0,0,0
30616,8497,bmw,i3,2017,21495,automatic,24041.0,hybrid,135.0,470.8,0.600000,46.0,3,0
35613,11068,bmw,i3,2016,16482,unknown,43695.0,hybrid,135.0,470.8,0.600000,81.0,1,0
36569,13430,bmw,i3,2017,19998,automatic,41146.0,hybrid,135.0,470.8,0.600000,69.0,1,0
36646,14531,bmw,i3,2017,18500,automatic,36429.0,hybrid,135.0,470.8,0.600000,30.0,2,0
38130,12332,bmw,i3,2015,14285,automatic,65800.0,hybrid,135.0,470.8,0.600000,50.0,3,0
39027,14512,bmw,i,2017,19000,automatic,23983.0,hybrid,135.0,470.8,0.000000,95.0,4,0
39368,10327,bmw,i3,2014,15450,automatic,42479.0,hybrid,135.0,470.8,0.600000,79.0,2,0
40327,11589,bmw,i3,2016,17100,automatic,25269.0,other,145.0,470.8,0.600000,97.0,0,0
48453,9643,bmw,i3,2017,19948,automatic,20929.0,hybrid,135.0,470.8,0.600000,71.0,2,0
49096,10967,bmw,i3,2016,17000,automatic,41063.0,other,145.0,470.8,0.600000,34.0,6,0
49745,9815,bmw,i3,2016,19875,automatic,20013.0,other,145.0,470.8,0.600000,30.0,0,0
53679,9196,bmw,i3,2016,19850,automatic,19995.0,hybrid,135.0,470.8,0.600000,79.0,3,0
53685,11962,bmw,i3,2017,22495,automatic,21025.0,hybrid,135.0,470.8,0.600000,66.0,0,0

In [115]:
train_cars.groupby(['Brand','fuelType'])['mpg'].mean().sort_values()

Brand     fuelType
mercedes  petrol       42.646520
bmw       petrol       43.285461
audi      petrol       46.495074
opel      petrol       48.344528
hyundai   petrol       50.435918
unknown   petrol       50.671849
audi      other        51.043288
opel      other        51.127095
vw        petrol       51.476780
toyota    diesel       52.287650
vw        other        53.407191
skoda     petrol       54.044163
audi      diesel       54.320654
unknown   other        55.062500
vw        diesel       55.272197
hyundai   other        55.358000
          diesel       55.811836
ford      petrol       55.867803
mercedes  other        56.264240
skoda     other        56.736762
ford      other        58.118528
toyota    petrol       58.265410
bmw       diesel       58.472257
mercedes  diesel       58.882067
unknown   diesel       59.052533
skoda     diesel       60.568587
ford      diesel       62.104597
toyota    other        63.379870
opel      diesel       63.582723
ford      electric     67.300000
hyundai   hybrid       71.860428
toyota    hybrid       75.323216
bmw       other        79.395139
unknown   hybrid       81.820588
ford      hybrid       89.270895
mercedes  hybrid      119.149989
vw        hybrid      123.450000
audi      hybrid      150.865000
bmw       hybrid      154.478613
skoda     hybrid      190.850000
opel      hybrid      235.400000
          electric    235.400000
unknown   electric    470.800000
Name: mpg, dtype: float64

In [97]:
outliers_low = train_cars['mpg'] < 10
outliers_high = train_cars['mpg'] > 150
train_cars.loc[outliers_low | outliers_high, 'mpg']

192      156.90000
260      151.04181
407      235.00000
629      151.04181
676      156.90000
           ...
56557    156.90000
57092    188.30000
57143    151.04181
57560    156.90000
57780    188.30000
Name: mpg, Length: 282, dtype: float64

## Outlier Detection